FROM oven/bun:latest

WORKDIR /usr/src/app

COPY ./bun.lock ./bun.lock

COPY turbo.json ./turbo.json

COPY packages ./packages

COPY package.json ./package.json

COPY apps/backend/package.json ./apps/backend/package.json

RUN bun install

COPY apps/backend ./apps/backend

RUN bun run generate:db

EXPOSE 8080

CMD ["bun" , "run" , "start:backend"]